# ![](https://ga-dash.s3.amazonaws.com/production/assets/logo-9f88ae6c9c3871690e33280fcf557f33.png) Noughts and Crosses

Week 9 | Morning Exercise 2.0

As a programming exercise let's make an Artificial Intelligence that can play noughts and crosses. Noughts and crosses is the game where you have a 3x3 board and you place either an X or a O to mark your move. You win by placing three of your marker in a row before your opponent achieves the same. You cannot play your move on top of the opponent's marker.

As a starting point, I suggest just writing a program where the computer selects a position to play at random (so not particularly intelligent). If you get that far you can think about how to make an algorithm such that the computer appears to have intelligence when playing. Of course, the aim with machine learning is to arrive at a way that an AI would not need to be explicitly programmed - but it's still interesting to think about how that explicit programming can be done, if only to avoid it!

We will do this as a pair exercise, and due to the complexity we will say that you can import modules to make things easier. It should also be possible to do it without.

# Solution

In [3]:
from __future__ import print_function
import numpy as np
import random
keyboard = np.array([[1,2,3],[4,5,6],[7,8,9]])
board = np.chararray((3,3))
moves_dict = {1:(0,0), 2:(0,1), 3:(0,2), 4:(1,0), 5:(1,1), 6:(1,2), 7:(2,0), 8:(2,1), 9:(2,2)}
wincombos = [board[0], board[1], board[2], board[:,0], board[:,1], board[:,2], board.diagonal(), np.fliplr(board).diagonal()]

def check_win(board):
    global endgame
    global win
    global lose
    
    for w in wincombos:
        w = list(w)
        if w.count('O') == 3:
            endgame = True
            lose = True
        
        if w.count('X') == 3:
            endgame = True
            win = True
    

def make_computer_move(board):
    '''Only makes random moves. 
    
    If you want to improve the game's AI, start here.
    '''
    #Make a random move 
    testx = random.randint(0,2)
    testy = random.randint(0,2)
    
    #Check if that space is occupied
    while board[testx][testy] != '-':
        testx = random.randint(0,2)
        testy = random.randint(0,2)


    x = testx
    y = testy 
    board[x][y] = 'O'
            
    return board

def make_player_move(board):
    move = int(input('Please enter your move (1-9): '))
    
    #Check if the input is valid
    if move < 1 or move > 9:
        while move < 1 or move > 9:
            move = int(input('That is an invalid move. Please re-enter your move: '))

    move_x, move_y = moves_dict[move]
    
    #Check if the space is taken
    while board[move_x][move_y] != '-':
        move = int(input('That is an invalid move. Please re-enter your move: '))
        move_x, move_y = moves_dict[move]

    board[move_x][move_y] = 'X'

    return board

def play_game():
    board[:] = '-'
    global endgame
    global win 
    global lose

    print(keyboard)
    print(board)

    while not endgame:

        make_player_move(board)
        check_win(board)

        if '-' not in board:
            endgame = True
            break

        make_computer_move(board)
        check_win(board)

        print(board)

    if win:
        print("You win")
    elif lose:
        print("Computer wins")
    elif endgame:
        print("Tie game")
    


In [4]:
endgame = False
win = False
lose = False

play_game()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[['-' '-' '-']
 ['-' '-' '-']
 ['-' '-' '-']]
Please enter your move (1-9): 1
[['X' '-' '-']
 ['O' '-' '-']
 ['-' '-' '-']]
Please enter your move (1-9): 2
[['X' 'X' '-']
 ['O' '-' '-']
 ['-' '-' 'O']]
Please enter your move (1-9): 3
[['X' 'X' 'X']
 ['O' '-' 'O']
 ['-' '-' 'O']]
You win
