In [ ]:
## Lab - NumPy

One of the main reasons you may want to reshape an array is to change its dimensions. Remember, a vector is a 1D array, a matrix is a 2D array, but arrays can have several dimensions. One example may be that you want to reshape a 3D array into a vector or a matrix, to make manipulating the data easier.

A reason you may want to transpose a data set is to transform it from a "tall and skinny" data set to a "short and fat" data set or vice versa. It depends on what type of analysis you're doing, but using transpose will help you put your data set in a format that is most conducive to what you want to accomplish. Hence it's an important thing to know how to do.

Requirements:
- Create an array
- Reshape the array
- Transpose the array
- Repeat the process with different sizes and shapes of the initial array

Bonus:
- Different ways to index the array


In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b = np.transpose(a)
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
b.reshape((1,6))

array([[1, 4, 2, 5, 3, 6]])

In [13]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [15]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
m = np.arange(6).reshape(2,3)
m

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
m[0]

array([0, 1, 2])

In [18]:
m[:,0]

array([0, 3])

In [19]:
m[1,2]

5

In [21]:
m[1][2]

5

In [29]:
np.argmax(m,axis=0)

array([1, 1, 1])