## Labs - Stats with Python

Standard deviation is a number used to tell how measurements for a group are spread out from the average (mean), or expected value. A low standard deviation means that most of the numbers are very close to the average. A high standard deviation means that the numbers are spread out.

Statisticians use variance to see how individual numbers relate to each other within a data set, rather than using broader mathematical techniques such as arranging numbers into quartiles. A drawback to variance is that it gives added weight to numbers far from the mean (outliers), since squaring these numbers can skew interpretations of the data.

Requirements:
- Write a function that computes the standard deviation of an array (try just a 1d array)
- Write a function that computes the variance
- Hint: what are the equations for these? The idea is to use numpy only to create the initial array but not its functions
- Compare the results of your functions to the results of the numpy standard deviation and variance functions


Bonus:
- Adjust the function to deal with different array shapes (e.g. 2d, 3d)
- Investigate how numpy implements these solutions and compare to your method

In [38]:
from __future__ import division
import random as rd
l = [rd.randint(0,100)for _ in range(10)]
l
import numpy as np
a = np.array(l)
print(a)

[64 78  9 86 54 12 67 87 40  0]


In [25]:
def var(arr):
    mean = sum(arr)/len(arr)
    deviance_sq = [(x - mean)**2 for x in arr]
    sd = sum(deviance_sq)/len(deviance_sq)
    return(sd)

print(var(a))
np.var(a)

719.0


719.0

In [26]:
def sd(arr):
    return(np.sqrt(var(arr)))

print(sd(a))
np.std(a)

26.8141753556


26.814175355583846

In [28]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
def sdnd(arr):
    size = arr.size
    print(arr)
    arr1d = arr.reshape(1,size)[0]
    print(arr1d)
    return(sd(arr1d))

print(sdnd(m))
np.std(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
2.58198889747


2.5819888974716112