# Feature Selection Methods in sklearn Lab

In this lab we will explore feature selection on the Titanic Dataset. First of all let's load a few things:

- The training set from lab 2.3
- The union we have saved in lab 2.3


You can load the titanic data as follows:

    psql -h dsi.c20gkj5cvu3l.us-east-1.rds.amazonaws.com -p 5432 -U dsi_student titanic
    password: gastudents

In [28]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

from sqlalchemy import create_engine
engine = create_engine('postgresql://dsi_student:gastudents@dsi.c20gkj5cvu3l.us-east-1.rds.amazonaws.com/titanic')

# We will pull in the Titanic data as before
df = pd.read_sql('SELECT * FROM train', engine)

In [29]:
df.head()

index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   
3      3            4         1       1   
4      4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  None        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  None        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  None        S

In [30]:
import gzip
import dill

# I've set up a preset union object here, from lab 2.3. You can complete the lab with this but you may find it more
# satisfying to load the version that you made in that lab (and hopefully saved as union.dill.gz)
with gzip.open('union_preset.dill.gz') as fin:
    union = dill.load(fin)
    
X = df[[u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch', u'Fare', u'Embarked']]
y = df[u'Survived']

X_transf = union.fit_transform(X)
X_transf[0]

array([-0.5924806 ,  0.        ,  1.        ,  0.        ,  1.        ,
        1.        , -0.50244517])

## 1 Column names

The column names have become lost along the way. We can manually add them back in:

`union = make_union(age_pipe, one_hot_pipe, gender_pipe, fare_pipe)`

- age_pipe => 'scaled_age'
- one_hot_pipe => 'Pclass_2', 'Pclass_3', 'Embarked_Q', 'Embarked_S'
- gender_pipe => 'male'
- fare_pipe => 'scaled_fare'

We need to:

1. Create a new pandas dataframe `Xt` with the appropriate column names and fill it with the `X_transf` data.
2. Notice that we discard the columns: u'SibSp', u'Parch', that is unless you covered this part in lab 2.3 (this was an optional bonus). So we ignore them in this analysis, unless you dealt with them there in which case do keep using them.
3. The order of columns should match the order you place the pipelines in the union; I have added the code I used above from lab 2.3 which was used to make the union_preset.dill.gz file. If you are importing your own union object you may wish to verify the code you used by reopening the notebook from lab 2.3.

**Check:** are you clear on why we do not have a dummy variable for Pclass_1 or Embarked_C?

In [31]:
col_names = ['scaled_age','Pclass_2','Pclass_3','Embarked_Q','Embarked_S','male','scaled_fare']
Xt = pd.DataFrame(X_transf,columns=col_names)
Xt.head(2)

scaled_age  Pclass_2  Pclass_3  Embarked_Q  Embarked_S  male  scaled_fare
0   -0.592481       0.0       1.0         0.0         1.0   1.0    -0.502445
1    0.638789       0.0       0.0         0.0         0.0   0.0     0.786845

## 2. Feature selection

Let's use the `SelectKBest` method in scikit learn to see which are the top 5 features (out of how many?). We will use the f test for classification method that we discussed in the lecture (this is actually the default but we import it just to be explicit about our methodology, this is particularly important for this approach because it can still give
results if you apply the test for a countinous output rather than a classification output - but this would be meaningless, hence always have a think about which test you are actually applying with these methods).

- What are the top 5 features for `Xt`?
- Check the methods associated with SelectKBest to see how to interact with it and return the columns of interest (eg get_support returns booleans you can use for indexing the dataframe)

=> store them in a variable called `kbest_columns`

In [103]:
from sklearn.feature_selection import SelectKBest, f_classif

# Check the documentation for SelectKBest, note that the f_classif
# is passed as an argument itself (i.e. not as a string)
selector = SelectKBest(k=5).fit(Xt,y)
print(selector.get_support())
kbest_columns = selector.get_support(indices=True)
kbest_columns

[False  True  True False  True  True  True]


array([1, 2, 4, 5, 6], dtype=int64)

In [96]:
# If you manage the above, you might be a bit unclear about how it has selected these
# top five. If you call selector.pvalues_ you can return the p value results of the
# comparisons of the inputs to see which are the more significant

print(selector.pvalues_)
print(Xt.columns)

[  3.72170837e-02   5.29365528e-03   5.51028100e-23   9.13353235e-01
   3.03611106e-06   1.40606613e-69   6.12018934e-15]
Index([u'scaled_age', u'Pclass_2', u'Pclass_3', u'Embarked_Q', u'Embarked_S',
       u'male', u'scaled_fare'],
      dtype='object')


## 3. Recursive Feature Elimination

`Scikit Learn` also offers recursive feature elimination as a class named `RFE`. Use it in combination with a logistic regression model to see what features would be kept with this method.

=> store them in a variable called `rfecv_columns`

In [108]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# Check the documentation for RFE. You can first instantiate the logistic 
# regression object, then pass it as an argument to the RFE
logreg = LogisticRegression()
selector = RFE(logreg)
selector.fit(Xt,y)

RFE(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
  n_features_to_select=None, step=1, verbose=0)

In [110]:
# These methods can reveal more and also can be used for boolean indexing of the features
rfecv_columns = selector.support_
print(rfecv_columns)
rfecv_columns = [1 if _ else 0 for _ in rfecv_columns]
print(rfecv_columns)
print(selector.ranking_)

[False  True  True False False  True False]
[0, 1, 1, 0, 0, 1, 0]
[3 1 1 5 2 1 4]


In [67]:
# Bonus - also try from sklearn.feature_selection import RFECV
from sklearn.feature_selection import RFECV
selector2 = RFECV(logreg,cv=5)
selector2.fit(Xt,y)

RFECV(cv=5,
   estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
   n_jobs=1, scoring=None, step=1, verbose=0)

In [68]:
print(selector2.support_)
print(selector2.ranking_)

[ True  True  True False  True  True  True]
[1 1 1 2 1 1 1]


## 4. Logistic regression coefficients

Let's see what we get with the Logistic Regression coefficients.

- Create a logistic regression model
- Perform grid search over penalty type and C strength in order to find the best parameters
- Sort the logistic regression coefficients by absolute value. Do the top 5 correspond to those above? They may not because these selection methods are distinct. So it's up to you to decide on the best approach.

=> choose which ones you would keep and store them in a variable called `lr_columns`

In [77]:
from sklearn.model_selection import GridSearchCV
logreg = LogisticRegression()
C_vals = [0.0001, 0.001, 0.01, 0.1, 0.5, 0.75, 1.0, 2.5, 5.0, 10.0, 100.0, 1000.0]
penalties = ['l1','l2']
gs = GridSearchCV(logreg, {'penalty':penalties, 'C':C_vals}, cv=5, scoring='accuracy')
gs.fit(Xt,y)
gs.best_params_

{'C': 100.0, 'penalty': 'l1'}

In [78]:
# This method can tell you which of the model instances performed best
gs.best_estimator_

LogisticRegression(C=100.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [134]:
gs_logreg = LogisticRegression(C=gs.best_params_["C"], penalty=gs.best_params_["penalty"], solver='liblinear')
gs_logreg.fit(Xt, y)
np.abs(gs_logreg.coef_)
lr_columns_order=[5,3,2,7,4,1,6]
lr_columns=      [0,1,1,0,1,1,0]
lr_columns_order

[5, 3, 2, 7, 4, 1, 6]

## 5. Compare features sets

Use the `best estimator` from question 4 on the 3 different feature sets:

- `kbest_columns`
- `rfecv_columns`
- `lr_columns`
- `all_columns`

Questions:

- Which scores the highest? (use cross_val_score)
- Is the difference significant?
- discuss in pairs

In [136]:
from sklearn.model_selection import cross_val_score
gs_logreg = LogisticRegression(C=gs.best_params_["C"], penalty=gs.best_params_["penalty"], solver='liblinear')

# Kbest
gs_logreg.fit(Xt[kbest_columns], y)
accuracies = cross_val_score(gs_logreg, Xt[kbest_columns], y, cv=5)
print(np.mean(accuracies))

# RFEcv
gs_logreg.fit(Xt[rfecv_columns], y)
accuracies = cross_val_score(gs_logreg, Xt[rfecv_columns], y, cv=5)
print(np.mean(accuracies))

# lr
gs_logreg.fit(Xt[lr_columns], y)
accuracies = cross_val_score(gs_logreg, Xt[lr_columns], y, cv=5)
print(np.mean(accuracies))

# all
gs_logreg.fit(Xt, y)
accuracies = cross_val_score(gs_logreg, Xt, y, cv=5)
print(np.mean(accuracies))

0.77330092663
0.619535553572
0.619535553572
0.79574180603


## Bonus

Use a bar chart to display the logistic regression coefficients. Start from the most negative on the left. Can you come up with bar chart rankings for the other methods also? How about a heat map like we talked about in the lecture?